/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activities;

import static activities.Fitness.Final_Heart_Rate;
import static activities.Fitness.Total_Calories_Burnt;
import javax.swing.JOptionPane;
import java.util.*; 

/**
 *
 * @author Nour
 */
public class Fitness_Tracker1 extends javax.swing.JFrame {
   public static int Swimming_Calories = 0;
   public static  float Swimming_Heart = 0;   
   public static  int Running_Calories = 0;
   public static  float Running_Heart = 0;    
   public static  int Boxing_Calories = 0;
   public static  float Boxing_Heart = 0;
   public static  int Strength_Calories = 0;
   public static  float Strength_Heart = 0;
   
    /**
     * Creates new form Fitness_Tracker
     */
    public Fitness_Tracker1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        List = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Timebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TotalC = new javax.swing.JTextField();
        TotalH = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("   Simple Fitness Tracker");

        List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming", "Running", "Kick_Boxing", "Strength_Training" }));
        List.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListComponentShown(evt);
            }
        });
        List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListActionPerformed(evt);
            }
        });

        jLabel2.setText(" Add Activity: ");

        jLabel3.setText(" Type:");

        Timebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeboxActionPerformed(evt);
            }
        });

        jLabel4.setText(" Time:");

        jLabel5.setText(" minutes");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText(" Total Calories Burnt =");

        jLabel7.setText("Total Heart Rate = ");

        jButton2.setText("Done For Today");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TotalC))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(List, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Timebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TotalH, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Timebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TotalC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TotalH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ListComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_ListComponentShown

    private void ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListActionPerformed
       
    }//GEN-LAST:event_ListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(List.getSelectedItem().equals("Swimming")){
      int time = Integer.parseInt(Timebox.getText());
    Athlete athlete = new Athlete();
    athlete.set();
    athlete.setInitial_Heart_Rate(Final_Heart_Rate);
    String Sport1 = "Swimming"; 
  
    Swimming_Calories = Swimming_Calories + time*4;
    Total_Calories_Burnt = Total_Calories_Burnt + athlete.Total_Calories_Burnt(Sport1, time);
    Final_Heart_Rate = athlete.CalcFinal_Heart_Rate(Sport1, time);
    Swimming_Heart = athlete.Heart_Rate_Increase;
    
    TotalC.setText(""+ Fitness.Total_Calories_Burnt);
    TotalH.setText("" + Fitness.Final_Heart_Rate);
    JOptionPane.showMessageDialog(null, "Activity Added Successfully");
        }
        
        else if(List.getSelectedItem().equals("Running")){
      int time = Integer.parseInt(Timebox.getText());
    Athlete athlete = new Athlete();
    athlete.set();
    athlete.setInitial_Heart_Rate(Final_Heart_Rate);
    String Sport1 = "Running";
    
    Running_Calories = Running_Calories + time*5;
    Total_Calories_Burnt = Total_Calories_Burnt + athlete.Total_Calories_Burnt(Sport1, time);
    Final_Heart_Rate = athlete.CalcFinal_Heart_Rate(Sport1, time);
    Running_Heart = athlete.Heart_Rate_Increase;
    
    TotalC.setText(""+ Fitness.Total_Calories_Burnt);
    TotalH.setText("" + Fitness.Final_Heart_Rate);
    JOptionPane.showMessageDialog(null, "Activity Added Successfully");
        }
        
        else if(List.getSelectedItem().equals("Kick_Boxing")){
     int time = Integer.parseInt(Timebox.getText());
    Athlete athlete = new Athlete();
    athlete.set();
    athlete.setInitial_Heart_Rate(Final_Heart_Rate);
    String Sport1 = "Kick_Boxing";    
    
    Boxing_Calories = Boxing_Calories + time*3;
    Total_Calories_Burnt = Total_Calories_Burnt + athlete.Total_Calories_Burnt(Sport1, time);
    Final_Heart_Rate = athlete.CalcFinal_Heart_Rate(Sport1, time);
    Boxing_Heart = athlete.Heart_Rate_Increase;
    
    TotalC.setText(""+ Fitness.Total_Calories_Burnt);
    TotalH.setText("" + Fitness.Final_Heart_Rate);
    JOptionPane.showMessageDialog(null, "Activity Added Successfully");
        }
        else if(List.getSelectedItem().equals("Strength_Training")){
        int time = Integer.parseInt(Timebox.getText());
    Athlete athlete = new Athlete();
    athlete.set();
    athlete.setInitial_Heart_Rate(Final_Heart_Rate);
    String Sport1 = "Strength_Training";
    
    Strength_Calories = Strength_Calories + time*5;
    Total_Calories_Burnt = Total_Calories_Burnt + athlete.Total_Calories_Burnt(Sport1, time);
    Final_Heart_Rate = athlete.CalcFinal_Heart_Rate(Sport1, time);     
    Strength_Heart = athlete.Heart_Rate_Increase;
    
    TotalC.setText(""+ Fitness.Total_Calories_Burnt);
    TotalH.setText("" + Fitness.Final_Heart_Rate);
    JOptionPane.showMessageDialog(null, "Activity Added Successfully");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TimeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Fitness_Tracker2 form = new Fitness_Tracker2();
    form.setVisible(true);
    
 
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> List;
    private javax.swing.JTextField Timebox;
    private javax.swing.JTextField TotalC;
    private javax.swing.JTextField TotalH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables


}
